package api

import (
	"encoding/json"
	"log/slog"
	"net/http"

	"github.com/aaayushm23/context-engine/internal/cache"
	contextpkg "github.com/aaayushm23/context-engine/internal/context"
	"github.com/aaayushm23/context-engine/internal/engine"
	"github.com/aaayushm23/context-engine/internal/events"
	"github.com/aaayushm23/context-engine/internal/partner"
	"github.com/aaayushm23/context-engine/pkg/models"
)

type Handler struct {
	pipeline       *contextpkg.Pipeline
	decisionEngine *engine.DecisionEngine
	partnerRepo    *partner.Repository
	cache          *cache.RedisCache
	publisher      *events.Publisher
	analytics      *events.AnalyticsConsumer
	logger         *slog.Logger
}

func NewHandler(
	pipeline *contextpkg.Pipeline,
	decisionEngine *engine.DecisionEngine,
	partnerRepo *partner.Repository,
	cache *cache.RedisCache,
	publisher *events.Publisher,
	analytics *events.AnalyticsConsumer,
	logger *slog.Logger,
) *Handler {
	return &Handler{
		pipeline:       pipeline,
		decisionEngine: decisionEngine,
		partnerRepo:    partnerRepo,
		cache:          cache,
		publisher:      publisher,
		analytics:      analytics,
		logger:         logger,
	}
}

// HandleRecommend acts as the primary orchestration point for the recommendation workflow.
// It translates the external HTTP contract into the internal domain model and delegates
// to the context pipeline and decision engine, adhering to the Hexagonal Architecture pattern.
func (h *Handler) HandleRecommend(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	var req models.RecommendationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid JSON: " + err.Error()})
		return
	}

	// We prioritize a client-provided request ID for end-to-end tracing originating outside the system,
// but fall back to the context-injected one generated by our middleware if absent.
	reqID, _ := r.Context().Value(RequestIDKey).(string)
	if req.RequestID != "" {
		reqID = req.RequestID
	}

	// The force-rules flag provides a deterministic testing seam and an explicit operational lever
// to bypass non-deterministic LLM behavior during critical moments or automated suite runs.
	forceRules := r.Header.Get("X-Force-Rules") == "true"

	// We construct the core model before any enrichment so that downstream components
// have a shared semantic boundary rather than relying on disparate loosely-typed inputs.
	rc := &models.RecommendationContext{
		RequestID:      reqID,
		Lat:            req.Lat,
		Lon:            req.Lon,
		AvailableHours: req.AvailableHours,
		Preferences:    req.Preferences,
	}

	// The pipeline executes enrichers concurrently to respect the firm latency budget.
// It is designed to be resilient: partial failures degrade gracefully without blocking the response.
	h.pipeline.Run(r.Context(), rc)

	// The decision engine abstracts the complexity of choosing between an LLM inference
// and static rules. This decoupling allows us to iterate on inference logic without touching the API layer.
	resp, err := h.decisionEngine.GenerateRecommendation(r.Context(), rc, forceRules)
	if err != nil {
		h.logger.Error("recommendation failed", "error", err, "request_id", reqID)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "recommendation failed"})
		return
	}

	// Event emission is pushed to a background goroutine to unblock the HTTP response.
// By doing this, we trade guaranteed event delivery for significantly reduced tail latencies.
	go h.publisher.PublishRecommendation(r.Context(), resp)

	writeJSON(w, http.StatusOK, resp)
}

// HandleListPartners provides a synchronized view of partner availability.
// It bypasses the complex decision pipeline and interacts directly with the repository
// for rapid read access backing administrative or debug dashboards.
func (h *Handler) HandleListPartners(w http.ResponseWriter, r *http.Request) {
	partners, err := h.partnerRepo.GetAll(r.Context())
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, partners)
}

// HandleHealth is the primary liveness/readiness probe used by orchestration platforms (e.g., Kubernetes).
// It verifies critical infrastructure dependencies because accepting traffic without them
// would only result in cascading downstream errors.
func (h *Handler) HandleHealth(w http.ResponseWriter, r *http.Request) {
	if err := h.partnerRepo.Ping(r.Context()); err != nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{
			"status": "unhealthy",
			"reason": "postgres: " + err.Error(),
		})
		return
	}
	if err := h.cache.Ping(r.Context()); err != nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{
			"status": "unhealthy",
			"reason": "redis: " + err.Error(),
		})
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{
		"status":  "healthy",
		"service": "context-engine",
	})
}

// HandleMetrics exposes internally tracked consumer state, facilitating white-box
// monitoring and autoscaling decisions based on application-level throughput.
func (h *Handler) HandleMetrics(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, h.analytics.Stats())
}

func writeJSON(w http.ResponseWriter, status int, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(data)
}
